### ISSUE TITLE
Can't swing sword at mobs?

### ISSUE THREAD

**Issue by u2695** [jaszlo/Playerautoma#5]
Hi, I'm trying to record a macro for an AFK farm but during the macro replay, the attacks aren't taking place? Other sword swings against items or blocks work. 

Video here: https://www.youtube.com/watch?v=G0pvYAD0lnQ

Minecraft 1.20.2
Playerautoma 0.3.1+1.20.2 (0.3.3 was crashing for me)

[edit] I forgot to save the replay to disk, but here is a similar one but without the swings onto regular blocks.  
[farm.rec.txt](https://github.com/jaszlo/Playerautoma/files/13925949/farm.rec.txt)

**Comment by jaszlo** [comment]
Just tested 0.3.3+1.20.2 in the production environment and it crashes on start. This is probably the same issue you encountered. I fixed this right away and inplace for v0.3.3+1.20.2. There was an issue with the build. So the new rebuild JAR available on [Modrinth](https://modrinth.com/mod/playerautoma/version/v0.3.3+1.20.2) or via [Github-Release](https://github.com/jaszlo/Playerautoma/releases/tag/v0.3.3%2B1.20.2) should work now!

If it still crashes please let me know.

**Comment by u2695** [comment]
Apologies for not providing the crash log, it was indeed happening when the game started up. The new version loaded fine and I was able to confirm the bug of not swinging my sword at an enemy mob was still happening when replaying actions. Thanks for looking into it! :)

**Comment by jaszlo** [comment]
No worries. Such an obvious mistake shouldn't have made it into a release in the first place. So thanks for reporting it.

Yeah the attacking will be fixed with the next update. Can't say however when that will be released.

**Comment by calebleung** [comment]
Thanks! I did a quick test and it worked. Much appreciated :)

**Comment by u2695** [comment]
Thanks. Gave it a quick test and it worked as expected. Much appreciated :)
